name: Deploy to GitHub Pages

# Trigger deployment on push to main branch or manual dispatch
on:
  push:
    branches: [main]
  workflow_dispatch:

# Grant permissions for Pages and OIDC token
permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build -- --base-href /analytify/ --output-path dist/preview
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/preview